// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZZAUFtquQT5QnxDNacwa1TXmjlof9NDY',
    appId: '1:494627254798:web:bf9403e140e95281c8025f',
    messagingSenderId: '494627254798',
    projectId: 'alarmapp-efe74',
    authDomain: 'alarmapp-efe74.firebaseapp.com',
    storageBucket: 'alarmapp-efe74.firebasestorage.app',
    measurementId: 'G-TM6YNDFNVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqsGX7kgTu5mkNx0CwJXyPd0PFirKM_Ew',
    appId: '1:494627254798:android:f99511877927cdddc8025f',
    messagingSenderId: '494627254798',
    projectId: 'alarmapp-efe74',
    storageBucket: 'alarmapp-efe74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAde6UZDzN1iPYWzT0ltzsVSk64RP2Uckw',
    appId: '1:494627254798:ios:6afd64d7328f77d6c8025f',
    messagingSenderId: '494627254798',
    projectId: 'alarmapp-efe74',
    storageBucket: 'alarmapp-efe74.firebasestorage.app',
    iosBundleId: 'com.example.alarmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAde6UZDzN1iPYWzT0ltzsVSk64RP2Uckw',
    appId: '1:494627254798:ios:6afd64d7328f77d6c8025f',
    messagingSenderId: '494627254798',
    projectId: 'alarmapp-efe74',
    storageBucket: 'alarmapp-efe74.firebasestorage.app',
    iosBundleId: 'com.example.alarmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZZAUFtquQT5QnxDNacwa1TXmjlof9NDY',
    appId: '1:494627254798:web:deb8b944e15c80dbc8025f',
    messagingSenderId: '494627254798',
    projectId: 'alarmapp-efe74',
    authDomain: 'alarmapp-efe74.firebaseapp.com',
    storageBucket: 'alarmapp-efe74.firebasestorage.app',
    measurementId: 'G-B1T73J36DJ',
  );
}
